### PR TITLE
#242 Fixed Contracts Table entries wrong display info.

### LINKED ISSUE #242: Table footnote doesn’t update correctly based on entries per page
1. Go to the Contracts of a specific repository
2. Change to show 25 entries
**Expected result**: In my case, should have been “Showing 1 to 2 of 2 entries”
**Actual result**: It display "Showing 1 to 25 of 25 entries"
image

### PR DESCRIPTION
**Pull request by criske**
Fixes #242

- cleanup contractsService.js - at the moment we're doing all paging and filtering locally with `dataTables`, so there's no need to simulate server side paging in that service.
- getAndAddContract.js - cleaner way to show loading image in Contracts table: removed `dataTableShowLoading` function in favor of using `language.loadingRecords` setup property of `dataTable`).

Self XDSD

### CODE REVIEW

**Comment by charlesmike** [comment]
@criske thank you for your Pull Request. I'll assign someone to review it soon.

**Comment by criske** [comment]
no bounty needed, it was mostly cleanup and some refactoring.

**Comment by charlesmike** [comment]
@amihaiemil please review this Pull Request. Deadline (when it should be merged or closed) is ``2021-01-01T16:48:06.854148``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

File: src/main/resources/public/js/getAndAddContracts.js [hunk 1]
```diff
@@ -230,173 +250,122 @@ var projectContractsCount = -1;
...
         function loadContracts() {
             $("#contracts").dataTable().fnDestroy();
             $("#contracts").dataTable({
-                //setup
-                serverSide:  true,
-                searching:   false,//searching not possible yet on server
-                ordering:    false,//same for ordering
-                //adapt DataTable request to Self-Paged API specification.
+                language: {
+                    loadingRecords: '<img src="/images/loading.svg" height="100">'
```
Comment (criske) [inline src/main/resources/public/js/getAndAddContracts.js:257]: @amihaiemil We could use the same aproach for the other invoice/task tables.
Basically 
```javascript
$("#table").dataTable({
     language: { loadingRecords: '<img src=...>' },
     ajax: function(_, callback){
         callRemote(...).then(remoteData => {
             callback({data: remoteData.map(toTableRow)})
         })
     }
});
```
Current loading for the other tables looks somewhat weird to me, table headers are pushed down by the svg:
loading_invoices

Comment (amihaiemil) [reply src/main/resources/public/js/getAndAddContracts.js:257]: @criske yes, definitely. I will open a ticket for it.

**Review by amihaiemil — COMMENTED** [review]
@criske looks good, thanks~

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
